package basedef

const (
	KeyNameUID             = "base_uid"
	KeyNameRoute           = "base_route"
	KeyNameError           = "base_error"
	KeyNameRequest         = "base_req"
	KeyNameResponse        = "base_rsp"
	GinKeyFormat           = "base_gin_format"
	GinKeyBody             = "base_gin_body"
	GinKeyWriteResponse    = "base_gin_writeResponse"
	KeyNamePlatform        = "base_platform"
	ContextBeginKey        = "base_begin"
	KeyNameContext         = "base_context"
	GinKeyContext          = "base_gin_context"
	KeyNameBaseSpanCtx     = "base_span_ctx"
	GinKeyCurrentCtx       = "base_gin_current_ctx"
	KeyNameFullMethod      = "base_full_method"
	KeyNameUseTrace        = "base_use_trace"
	KeyNameReqID           = "base_reqid"
	KeyNameRemoteIP        = "base_remote_ip"
	KeyNameRemoteSrv       = "base_remote_srv"
	KeyNameService         = "base_service"
	KeyNameRootSpan        = "base_root_span"
	CacheKeyPrefix         = "_basecache"
	KeyNameIsLocal         = "base_is_local"
	KeyNameRpcName         = "base_rpc_name"
	KeyNameCurrentSpan     = "base_current_span"
	KeyNameGrpcPacketHead  = "base_packet_head"
	KeyNameSetDBCallPrefix = "base_set_db_call"
	KeyNameSetDBCallFormat = KeyNameSetDBCallPrefix + "_%s"
)
